### ISSUE TITLE
in firebase posturl is empty thats why error occures that No host specified in URI

### ISSUE THREAD

**Issue by Dipeshbhatt215** [AhmedAbdoElhawary/flutter-clean-architecture-instagram#187]

**Comment by AhmedAbdoElhawary** [comment]
Ok,
Look, I put a condition in this branch #190 to remove any post that has an empty URL.
Again when I publish a post it works with me.
I think that your firestore has docs containing an empty URL from your old fork.
Please, the next time gives me more details like snapshots or videos like I do to save my time.
Here is a recorded video of when the post was created.
https://user-images.githubusercontent.com/88978546/182969171-fce2386e-1230-4bb1-9e48-ea6a0d094da7.mp4
