### ISSUE TITLE
init method

### ISSUE THREAD

**Issue by bedirhanssaglam** [AhmedAbdoElhawary/flutter-clean-architecture-instagram#285]
If you run the init method on the splash screen, the application will not open slowly when opening.

**Comment by AhmedAbdoElhawary** [comment]
You mean, will open slowly. I know that.
But, Do you mean the one on the main, home page, multiBloc, or what?

**Comment by bedirhanssaglam** [comment]
I just wanted to offer a best practice solution. So what you are doing is not wrong :)
You can run this method on the splash screen.Future<SharedPreferences> init() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await initializeDependencies();
  await GetStorage.init();
  if (!kIsWeb) {
    await crashlytics();
    SystemChrome.setPreferredOrientations(
        [DeviceOrientation.portraitDown, DeviceOrientation.portraitUp]);
  }

  return await SharedPreferences.getInstance();
}

**Comment by AhmedAbdoElhawary** [comment]
Ok,
thank you for noticing.
You can check this branch #292
