### ISSUE TITLE
model folders

### ISSUE THREAD

**Issue by bedirhanssaglam** [AhmedAbdoElhawary/flutter-clean-architecture-instagram#288]
JsonSerializable or Freezed libraries should definitely be used for toJson fromJson operations.

**Comment by AhmedAbdoElhawary** [comment]
It's not should to use them. we don't use this word in software.

There are other ways to make it. in this case, I used "JSON to Dart" website.
If you want to say those packages are easy and save your time and make you write less code, I agree with you. They are so good.
In this project, I used the older way. But, I used those packages in other projects you can take a look at earlier projects in my profile.

**Comment by bedirhanssaglam** [comment]
It's not right doesn't mean it's wrong. It's not true, it means it's not best practice. Yes, I saw it in your other projects, well done :)
