### ISSUE TITLE
folder and file names

### ISSUE THREAD

**Issue by bedirhanssaglam** [AhmedAbdoElhawary/flutter-clean-architecture-instagram#289]
The folder and file names do not match. For example, under the customRoutes folder, there is the hero_dialog_route file. This makes it difficult to read.

**Comment by AhmedAbdoElhawary** [comment]
Maybe we can make hero_dialog_route with app_routes.
Or, update the folder name to customRoute.
But, I make a customRoutes folder, which means a custom route like material and Cupertino page routes
