### ISSUE TITLE
home videos

### ISSUE THREAD

**Issue by charliepitoy** [AhmedAbdoElhawary/flutter-clean-architecture-instagram#290]
is it just me who cant play the the home videos

**Comment by AhmedAbdoElhawary** [comment]
Could you explain more about your issue?

**Comment by charliepitoy** [comment]
> Could you explain more about your issue?

home post videos and profile videos are not playing it only shows the cover image of the video but its playing the audio of the video. on video page its okay its playing the video

**Comment by AhmedAbdoElhawary** [comment]
Could you show me a video screen to identify the issues faster?

**Comment by charliepitoy** [comment]
this is the home video issue
https://user-images.githubusercontent.com/114567923/209533328-b59e7336-8e47-4d71-aae9-bb5148b1a474.mp4

this is the video playing in video page it has no problem
https://user-images.githubusercontent.com/114567923/209533795-acc12390-3107-495d-9bda-48648ee39091.mp4

notification issue
https://user-images.githubusercontent.com/114567923/209534007-0220e04b-ccd6-4f57-8da8-ab57f97844df.mp4

**Comment by charliepitoy** [comment]
i think the notification issue is when commenting and liking the video post but the image has no issue

**Comment by AhmedAbdoElhawary** [comment]
Ok, you can check this branch #291
