### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by not-sociable** [AhmedAbdoElhawary/flutter-clean-architecture-instagram#324]
Hi! I am very grateful for the wonderful and open project! 
Could you tell me what could be the problem when building the project?
![image](https://github.com/AhmedAbdoElhawary/flutter-clean-architecture-instagram/assets/143441436/89f1ad56-dbbd-41e6-95fa-9710767627e8)

**Comment by AhmedAbdoElhawary** [comment]
Hi! Thanks for your appreciation.
It was a problem with the sliding sheet package. there is no GitHub repo, so I copied the package into the project and solved it.
the accentColor is now replaced by ColorScheme.secondary

**Comment by not-sociable** [comment]
> Hi! Thanks for your appreciation. It was a problem with the sliding sheet package. there is no GitHub repo, so I copied the package into the project and solved it. the accentColor is now replaced by ColorScheme.secondary

hi. 
Thank you for solving the problem instantly, your solution to the problem fixed the error. As a result, I can only build a Web project but not an android, why? 
![image](https://github.com/AhmedAbdoElhawary/flutter-clean-architecture-instagram/assets/143441436/72f04101-7e29-472f-9094-ac1997a05004)
